### ISSUE TITLE
MATE Volume OSD is missing its bar.

### ISSUE THREAD

**Issue by mz1193** [thesquash/gtk-theme-raleigh#3]
Hi Gordon, great work on the theme! Just wanted to let you know that the MATE Volume OSD is missing its bar when adjusting the volume. This only happens when Marco's compositing is enabled:
![volumeosd](https://user-images.githubusercontent.com/38786879/158610718-e5ea215f-ba78-414f-b474-5c144bd53dc1.png)

**Comment by thesquash** [comment]
Apparently MATE still uses deprecated style classes instead of real progress bar "object names", at least where the popups are concerned.  To compensate, I added style rules for legacy progress bar style classes as well, and the volume level shows up just fine now (as far as I can tell).

Closed by: 6ed6954329d74112fbd601b23337e76e73f6e43a.

Thanks for having such a keen eye!  People like you are part of the reason this theme keeps getting developed!
